"""Finds the Uniform Case Number in a document, email body, or subject."""

import re

from logger import get_logger

# Florida UCN. Three printed forms seen in real documents:
#   53-2026-CF-003351-A000-BA   dashes between every segment
#   53-2026CF-005480-A0-00BA    dashes in arbitrary places
#   532026CF005480A000BA        no dashes at all
#
# Rather than guess where dashes land, dashes are stripped from the text
# before matching and the underlying character shape is matched:
#   53      county (53 = Polk)
#   2026    filing year
#   CF      court type
#   005480  sequence
#   A000    party
#   BA      division
#
# The full 20 characters are required. A shorter pattern with dashes removed
# would match dates, docket numbers, and bates stamps.
UCN_PATTERN = re.compile(r"(?<!\d)(\d{6}[A-Z]{2}\d{6}[A-Z]\d{3}[A-Z]{2})")

logger = get_logger(__name__)

def find_ucn(document_text: str, body: str = "", subject: str = "") -> str | None:
    """Return the first UCN found, searching subject, then body, then document.

    The email subject is authoritative. It is generated by the e-filing portal
    from the case the filing was made under, so it carries exactly one UCN.
    Document text is the last resort: filings routinely cite prior cases, so a
    document can contain several UCNs with no reliable way to tell which is the
    caption.

    Only the extracted UCN is meant to be logged. Body and subject text is read
    here but must never be written to the audit log, since it carries party
    names.
    """
    for source_name, text in (
        ("subject", subject),
        ("body", body),
        ("document", document_text),
    ):
        if not text:
            continue

        matches = _find_all(text)
        if not matches:
            continue

        if len(set(matches)) > 1:
            logger.debug(
                "%s contains %s distinct UCNs, using the first",
                source_name,
                len(set(matches)),
            )

        logger.debug("UCN found in %s", source_name)
        return matches[0]

    return None

def _find_all(text: str) -> list[str]:
    """Return every UCN in the text, in order of appearance, normalized.

    Whitespace and dashes are stripped first, so all three printed forms
    match. Returned values are therefore in the run-together form regardless
    of how the document printed them.
    """
    stripped = re.sub(r"[\s-]+", "", text).upper()
    return UCN_PATTERN.findall(stripped)

def normalize(ucn: str) -> str:
    """Strip formatting so the two printed forms compare equal.

    532026CF005480A000BA and 53-2026-CF-005480-A000-BA both return
    532026CF005480A000BA. Short dashed forms that omit trailing segments
    will not equal a full one, which is correct: they are less specific.
    """
    return ucn.replace("-", "").upper()